[workspace]
members = [
    "pac/atsam4e16c",
    "pac/atsam4e16e",
    "pac/atsam4e8c",
    "pac/atsam4e8e",
    "pac/atsam4s2a",
    "pac/atsam4s2b",
    "pac/atsam4s2c",
    "pac/atsam4s4a",
    "pac/atsam4s4b",
    "pac/atsam4s4c",
    "pac/atsam4s8b",
    "pac/atsam4s8c",
    "pac/atsam4sa16b",
    "pac/atsam4sa16c",
    "pac/atsam4sd16b",
    "pac/atsam4sd16c",
    "pac/atsam4sd32b",
    "pac/atsam4sd32c",
]
